import type { CurrentUser } from './types';

const branch = { id: 'demo-branch', name: 'Velpadi Main Branch', code: 'VLR-01', city: 'Vellore', state: 'Tamil Nadu', phone: '9043420099', is_active: true, created_at: '2026-01-01T00:00:00Z', updated_at: '2026-01-01T00:00:00Z' };
const scheme = { id: 'demo-scheme', name: 'Gold Scheme - A1 (1L)', scheme_code: 'GOLD-A1-1L', chit_amount: '100000.00', member_count: 10, duration_periods: 10, frequency: 'monthly', installment_amount: '10000.00', max_bid_percent: '30.00', commission_percent: '5.00', is_active: true, created_at: '2026-01-01T00:00:00Z', updated_at: '2026-01-01T00:00:00Z' };
const group = { id: 'demo-group', group_code: 'GOLD-A1-1L-2026-01', start_date: '2026-01-01', end_date: '2026-10-31', status: 'active', current_cycle: 2, scheme_id: scheme.id, scheme_name: scheme.name, chit_amount: scheme.chit_amount, member_count: 10, frequency: 'monthly', branch_id: branch.id, branch_name: branch.name, created_at: '2026-01-01T00:00:00Z', updated_at: '2026-01-01T00:00:00Z' };
const customer = { id: 'demo-customer', full_name: 'Test Customer One', phone: '9111111101', email: 'test.customer1@example.com', city: 'Vellore', state: 'Tamil Nadu', pincode: '632001', kyc_status: 'verified', is_active: true, branch_id: branch.id, branch_name: branch.name, assigned_staff_id: 'demo-staff', assigned_staff_name: 'Dev Staff One', created_at: '2026-01-01T00:00:00Z', updated_at: '2026-01-01T00:00:00Z' };
const lead = { id: 'demo-lead', full_name: 'Test Lead One', phone: '9222222201', email: 'test.lead1@example.com', source: 'website', status: 'new', notes: 'Demo enquiry for Gold Scheme A1.', interested_scheme_id: scheme.id, interested_scheme_name: scheme.name, branch_id: branch.id, branch_name: branch.name, assigned_staff_id: 'demo-staff', assigned_staff_name: 'Dev Staff One', converted_customer_id: null, created_at: '2026-02-01T00:00:00Z', updated_at: '2026-02-01T00:00:00Z' };
const member = { id: 'demo-member', member_serial_no: 1, status: 'active', join_date: '2026-01-01', exit_date: null, exit_reason: null, customer_id: customer.id, customer_name: customer.full_name, customer_phone: customer.phone, chit_group_id: group.id, group_code: group.group_code, scheme_name: scheme.name, created_at: '2026-01-01T00:00:00Z', updated_at: '2026-01-01T00:00:00Z' };
const payment = { id: 'demo-payment', amount: '10000.00', payment_method: 'upi', reference_number: 'UPI-DEMO-0001', payment_date: '2026-02-05T10:00:00Z', status: 'success', notes: 'Demo payment', installment_id: 'demo-installment', cycle_number: 2, due_amount: '10000.00', due_date: '2026-02-05', chit_member_id: member.id, customer_name: customer.full_name, group_code: group.group_code, scheme_name: scheme.name, collected_by: 'demo-staff', collected_by_name: 'Dev Staff One', receipt_number: 'RCPT-DEMO-0001', created_at: '2026-02-05T10:00:00Z' };
const installment = { id: 'demo-installment', cycle_number: 2, due_date: '2026-02-05', due_amount: '10000.00', paid_amount: '10000.00', status: 'paid', chit_member_id: member.id, customer_name: customer.full_name, customer_phone: customer.phone, group_code: group.group_code, scheme_name: scheme.name, created_at: '2026-02-01T00:00:00Z', updated_at: '2026-02-05T10:00:00Z' };
const auction = { id: 'demo-auction', cycle_number: 3, scheduled_at: '2026-03-10T18:00:00+05:30', status: 'scheduled', winning_bid_percent: null, prize_amount: null, commission_amount: null, notes: 'Demo scheduled auction', chit_group_id: group.id, group_code: group.group_code, scheme_name: scheme.name, chit_amount: scheme.chit_amount, scheme_commission_percent: scheme.commission_percent, winning_member_id: null, winning_customer_name: null, conducted_by: null, conducted_by_name: null, created_at: '2026-02-01T00:00:00Z', updated_at: '2026-02-01T00:00:00Z' };

export const demoUser: CurrentUser = { id: 'demo-user', full_name: 'Dev Admin One', phone: '9000000001', email: 'dev.admin@example.com', user_type: 'staff', roles: ['Super Admin'], permissions: ['users:read', 'users:write', 'users:delete', 'roles:read', 'roles:write', 'staff:read', 'staff:write', 'staff:delete', 'branches:read', 'branches:write', 'branches:delete', 'leads:read', 'leads:write', 'leads:delete', 'customers:read', 'customers:write', 'customers:delete', 'chit_schemes:read', 'chit_schemes:write', 'chit_schemes:delete', 'chit_groups:read', 'chit_groups:write', 'chit_groups:delete', 'chit_members:read', 'chit_members:write', 'chit_members:delete', 'installments:read', 'installments:write', 'payments:read', 'payments:write', 'payments:delete', 'auctions:read', 'auctions:write', 'auctions:delete', 'notifications:read', 'notifications:write', 'whatsapp:read', 'whatsapp:write'] };

export function demoListForPath(path: string): Record<string, unknown>[] {
  if (path.startsWith('/leads')) return [lead];
  if (path.startsWith('/customers')) return [customer];
  if (path.startsWith('/staff')) return [{ id: 'demo-staff', employee_code: 'EMP-003', designation: 'Collections Staff', joining_date: '2024-06-01', is_active: true, branch_id: branch.id, branch_name: branch.name, user_id: 'demo-user', full_name: 'Dev Staff One', phone: '9000000003', email: 'dev.staff@example.com', roles: [{ id: 'demo-role', name: 'Staff' }], created_at: '2026-01-01T00:00:00Z', updated_at: '2026-01-01T00:00:00Z' }];
  if (path.startsWith('/branches')) return [branch];
  if (path.startsWith('/chit-schemes')) return [scheme];
  if (path.startsWith('/chit-groups')) return [group];
  if (path.startsWith('/chit-members')) return [member];
  if (path.startsWith('/installments')) return [installment];
  if (path.startsWith('/payments')) return [payment];
  if (path.startsWith('/auctions')) return [auction];
  if (path.startsWith('/notifications')) return [{ id: 'demo-notification', type: 'payment', title: 'Demo payment received', body: 'A demo payment was recorded for Test Customer One.', related_entity_type: 'payment', related_entity_id: payment.id, is_read: false, read_at: null, created_at: '2026-02-05T10:00:00Z' }];
  return [];
}

export const demoCounts = { totalLeads: 1, newLeads: 1, customers: 1, activeChitMembers: 1, pendingPayments: 0, overduePayments: 0, todaysCollection: 10000, upcomingAuctions: 1 };
